sudo: required

language: generic

services:
  - docker

env:
  - PHP_VERSION=7 MYSQL_VERSION=5.7
  - PHP_VERSION=7 MYSQL_VERSION=5.6
#  - PHP_VERSION=5.6 MYSQL_VERSION=5.7
#  - PHP_VERSION=5.6 MYSQL_VERSION=5.6

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - cd tests
  - docker-compose up -d ximdex

script:
  - docker-compose run test
  
notifications:
  email:
    recipients:
      - travis@ximdex.com
    on_success: change # default: change
    on_failure: always # default: always